### ISSUE TITLE
大佬，请问这个农历提醒系统，还会继续深化吗？

### ISSUE THREAD

**Issue by shengmean** [tiantianwahaha/Birthday-Reminder#1]
比如docker、web界面、阴阳历添加自动转换（目前只能添阴历）、企业微信提醒、提前3天5天通知、通讯录同步、导入导出、多用户、TGbot等功能。

**Comment by tiantianwahaha** [comment]
> 比如docker、web界面、阴阳历添加自动转换（目前只能添阴历）、企业微信提醒、提前3天5天通知、通讯录同步、导入导出、多用户、TGbot等功能。

抱歉，之前上传之后就没再管过。我更新了企业微信提醒，自用已经够了，其他功能应该不会写了...可以自行扩展

**Comment by tiantianwahaha** [comment]
close
